Fixed SA-23/9M82M guidance issue (hopefully)
Auranis/HighDigitSAMs pull request #26
Opened 2021-04-19 17:39 UTC by LetMePickThat

Changed the "9M82M" display name to "SA9M82".

2021-04-19 20:21 UTC, LetMePickThat commented
- fixed the gudance issue introduced by 2.7,
- changed the number of trackers on the 9S32ME from 6 to 24, in accordance w. Rosoboronexport's documentation.

2021-04-24 20:40 UTC, Auranis requested changes
Is the 51p6A.edm intended to be used right now, or are we just staging it for use by a new unit later?

2021-04-24 20:40 UTC, Auranis commented on Mods/tech/HighDigitSAMs/Database/Vehicle/5P85SE2 S-300PMU2 LN.lua
> +GT.visual.shape = "5985se";
Looks like a typo?

2021-04-24 20:56 UTC, LetMePickThat commented
> Is the 51p6A.edm intended to be used right now, or are we just staging it for use by a new unit later?

I will use it for another unit later on. I wanted to intoduce all 3D models for the future system (the 51P6A and the 92N6E) at the same time for simplicity. As the 92n6_truck.edm model is now used for the PMU2 for the 92N6E radar in place of the old 30N6 model, I added the TEL too.

2021-04-24 21:03 UTC, LetMePickThat commented on Mods/tech/HighDigitSAMs/Database/Vehicle/5P85SE2 S-300PMU2 LN.lua
> +GT.visual.shape = "5985se";
Yes, sorry.
It should read "5p85se" and "5p85se_d".
I made the change because I was told that the "smart" TELs on the PMU2 used smaller size electronics compared to old 300PS/PMU1 smart TELs, and therefore were closer look-wise to the older "dumb" TELs.

2021-04-24 21:09 UTC, merged