Numerous updates
Auranis/HighDigitSAMs pull request #37
Opened 2021-07-23 18:47 UTC by LetMePickThat

- Changed max range for low altitude shots for most 48N6 and 9M82/3 missiles versions to better reflect the long-range capabilities of these missile (see: https://forums.eagle.ru/topic/269447-high-digit-sams-a-community-asset-pack-for-dcs-world/?do=findComment&comment=4677272),
- Added new 3D models for the SAMP/T and SAMP/T NG,
- Added a first version of the SAMP/T and SAMP/T NG,
- Updated S-300V and S-300VM 3D models,
- Updated default textures for the S-300V (now using a common three-tone late-1990s Russian camo),
- Added 3D models and .lua files for a first version of the S-400 (relevant entry.lua lines commented out to avoid releasing prematurely, the system still requires some work - adding the 9M96E/9M96E2 missiles for instance).

2021-07-31 19:09 UTC, Auranis requested changes
New .lua files referenced in the entry.lua are missing.

2021-07-31 19:09 UTC, Auranis commented on Mods/tech/HighDigitSAMs/entry.lua
> +weapon_file("/Database/Weapon/48N6DM.lua")
This file is missing.

2021-07-31 19:09 UTC, Auranis commented on Mods/tech/HighDigitSAMs/entry.lua
> +weapon_file("/Database/Weapon/Aster_30_Blk_1.lua")
Aster 30 weapon files are missing.

2021-07-31 19:09 UTC, Auranis commented on Mods/tech/HighDigitSAMs/entry.lua
> +-- S-400
New vehicle .luas are missing.

2021-09-12 08:34 UTC, LetMePickThat commented
I wrote the requested changes.
All lines related to non-released systems are now removed.

2021-09-15 00:19 UTC, merged