Adding SAMP/T Block 1, Block 1NT and Block 2 (and other changes)
Auranis/HighDigitSAMs pull request #55
Opened 2024-05-17 23:06 UTC by zahnatom

I was bored
So idk I wrote the code for this, the models and textures were already there

no guarantees for accurate performance though

2024-06-05 07:51 UTC, YoloWingPixie requested changes
I've added my comments to this, looks very good. Some small things I'd like to see worked out personally.

2024-06-05 07:51 UTC, YoloWingPixie commented on Mods/tech/HighDigitSAMs/Database/Weapon/ASTER-30-1.lua
> +				50000.0 ,1.0,		-- Less 5 km to target Pn = 1
You have 50km set here, not 5km. I do not think you want to be full lead guidance at 50km

2024-06-05 07:51 UTC, YoloWingPixie commented on Mods/tech/HighDigitSAMs/Database/Weapon/ASTER-30-1.lua
> +GT_t.LN_t.Aster30_1.ECM_K = 0
Again, I believe this should be 0.1 or 0.2, not a flat 0.

2024-06-05 07:51 UTC, YoloWingPixie commented on Mods/tech/HighDigitSAMs/Database/Weapon/ASTER-30-1NT.lua
> +    Mach_max 		= 5.0,
Same question as the Blk1, where does this value come from?

2024-06-05 07:51 UTC, YoloWingPixie commented on Mods/tech/HighDigitSAMs/Database/Weapon/ASTER-30-1NT.lua
> +GT_t.LN_t.Aster30_1NT.ECM_K = 0
Same comment as before, 0.1/0.2 not 0.

2024-06-05 07:51 UTC, YoloWingPixie commented on Mods/tech/HighDigitSAMs/Database/Weapon/ASTER-30-2.lua
> +				100000.0 ,1.0,		-- Less 5 km to target Pn = 1
Here we have full lead guidance being implemented at 100km, I do not think this is what you intend. That is a lot of wasted energy if the target manuevers.

2024-06-05 07:51 UTC, YoloWingPixie commented on Mods/tech/HighDigitSAMs/Database/Weapon/ASTER-30-1.lua
> +	sigma 			= {10, 10, 10},
Seems kind of low, I think `{20, 20, 20}` would be a little more representative

2024-06-05 07:51 UTC, YoloWingPixie commented on Mods/tech/HighDigitSAMs/Database/Weapon/ASTER-30-1NT.lua
Consistent whitespace issues here too

2024-06-05 07:51 UTC, YoloWingPixie commented on Mods/tech/HighDigitSAMs/Database/Weapon/ASTER-30-2.lua
Consistent whitespace issues

2024-06-24 20:47 UTC, YoloWingPixie commented
Might have been a display issue, it looks like most of the whitespace is justified now. 

I or @Auranis will test again soon

2024-06-25 14:44 UTC, YoloWingPixie commented
Yep, we've encountered the same thing with the SA-20 missiles. It was fixable for us by switching over to `PN_Gain` and then cranking it up until the missile barely stays below the altitude limit before it'll escape into space with a worst case target.

2024-06-28 14:49 UTC, YoloWingPixie commented
Please undo that change, that's already in another pull request

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: zahnatom ***@***.***>
Sent: Friday, June 28, 2024 6:56:25 AM
To: Auranis/HighDigitSAMs ***@***.***>
Cc: Zachary Maynard ***@***.***>; Comment ***@***.***>
Subject: Re: [Auranis/HighDigitSAMs] Adding SAMP/T Block 1, Block 1NT and Block 2 (and other changes) (PR #55)


Decided to fix the SA-23 launchers as well as making the SA-20 missiles not spin out
Hope thats ok

—
Reply to this email directly, view it on GitHub<https://github.com/Auranis/HighDigitSAMs/pull/55#issuecomment-2196984076>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/AT5UARINV43W42YLYFIAI3TZJVTQTAVCNFSM6AAAAABI2ERX6SVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCOJWHE4DIMBXGY>.
You are receiving this because you commented.Message ID: ***@***.***>

2024-06-28 14:50 UTC, YoloWingPixie commented
Please undo the changes to the 48N6 and 48N6E2, there's already changes to those missiles in #53

2024-07-14 23:10 UTC, Auranis commented
Thanks for your implementation @zahnatom we will include this in the upcoming release.

2024-07-14 23:11 UTC, merged